//
// Copyright (c) 2015 Liviu Ionescu.
// This file was automatically generated by the xPacks scripts.
//

// The list of external handlers is from the ARM assembly startup files.

// ----------------------------------------------------------------------------

#include <cmsis-plus/cortexm/exception-handlers.h>

// ----------------------------------------------------------------------------

void __attribute__((weak))
Default_Handler(void);

// Forward declaration of the specific IRQ handlers. These are aliased
// to the Default_Handler, which is a 'forever' loop. When the application
// defines a handler (with the same name), this will automatically take
// precedence over these weak definitions

void __attribute__ ((weak, alias ("Default_Handler")))
EMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FRC_PRI_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
WDOG0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
WDOG1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FRC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
MODEM_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RAC_SEQ_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RAC_RSM_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
BUFC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LDMA_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_EVEN_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ACMP0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ADC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
IDAC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_ODD_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LEUART0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
MSC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CRYPTO0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LETIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
AGC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PROTIMER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RTCC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SYNTH_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CRYOTIMER_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RFSENSE_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FPUEH_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
SMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
WTIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
WTIMER1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART2_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART2_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART3_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART3_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
VDAC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CSEN_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LESENSE_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CRYPTO1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TRNG0_IRQHandler(void);

// ----------------------------------------------------------------------------

extern unsigned int _estack;

typedef void
(* const pHandler)(void);

// ----------------------------------------------------------------------------

// The table of interrupt handlers. It has an explicit section name
// and relies on the linker script to place it at the correct location
// in memory.

__attribute__ ((section(".isr_vector"),used))
pHandler __isr_vectors[] =
  {
    // Cortex-M Core Handlers
    (pHandler) &_estack,               // The initial stack pointer
    Reset_Handler,                     // The reset handler

    NMI_Handler,                       // The NMI handler
    HardFault_Handler,                 // The hard fault handler

#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    MemManage_Handler,                 // The MPU fault handler
    BusFault_Handler,                  // The bus fault handler
    UsageFault_Handler,                // The usage fault handler
#else
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    SVC_Handler,                       // SVCall handler
#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    DebugMon_Handler,                  // Debug monitor handler
#else
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    PendSV_Handler,                    // The PendSV handler
    SysTick_Handler,                   // The SysTick handler

    // ----------------------------------------------------------------------
    // External Interrupts
    EMU_IRQHandler,        // 0: EMU Interrupt
    FRC_PRI_IRQHandler,        // 1: FRC_PRI Interrupt
    WDOG0_IRQHandler,        // 2: WDOG0 Interrupt
    WDOG1_IRQHandler,        // 3: WDOG1 Interrupt
    FRC_IRQHandler,        // 4: FRC Interrupt
    MODEM_IRQHandler,        // 5: MODEM Interrupt
    RAC_SEQ_IRQHandler,        // 6: RAC_SEQ Interrupt
    RAC_RSM_IRQHandler,        // 7: RAC_RSM Interrupt
    BUFC_IRQHandler,        // 8: BUFC Interrupt
    LDMA_IRQHandler,        // 9: LDMA Interrupt
    GPIO_EVEN_IRQHandler,        // 10: GPIO_EVEN Interrupt
    TIMER0_IRQHandler,        // 11: TIMER0 Interrupt
    USART0_RX_IRQHandler,        // 12: USART0_RX Interrupt
    USART0_TX_IRQHandler,        // 13: USART0_TX Interrupt
    ACMP0_IRQHandler,        // 14: ACMP0 Interrupt
    ADC0_IRQHandler,        // 15: ADC0 Interrupt
    IDAC0_IRQHandler,        // 16: IDAC0 Interrupt
    I2C0_IRQHandler,        // 17: I2C0 Interrupt
    GPIO_ODD_IRQHandler,        // 18: GPIO_ODD Interrupt
    TIMER1_IRQHandler,        // 19: TIMER1 Interrupt
    USART1_RX_IRQHandler,        // 20: USART1_RX Interrupt
    USART1_TX_IRQHandler,        // 21: USART1_TX Interrupt
    LEUART0_IRQHandler,        // 22: LEUART0 Interrupt
    PCNT0_IRQHandler,        // 23: PCNT0 Interrupt
    CMU_IRQHandler,        // 24: CMU Interrupt
    MSC_IRQHandler,        // 25: MSC Interrupt
    CRYPTO0_IRQHandler,        // 26: CRYPTO0 Interrupt
    LETIMER0_IRQHandler,        // 27: LETIMER0 Interrupt
    AGC_IRQHandler,        // 28: AGC Interrupt
    PROTIMER_IRQHandler,        // 29: PROTIMER Interrupt
    RTCC_IRQHandler,        // 30: RTCC Interrupt
    SYNTH_IRQHandler,        // 31: SYNTH Interrupt
    CRYOTIMER_IRQHandler,        // 32: CRYOTIMER Interrupt
    RFSENSE_IRQHandler,        // 33: RFSENSE Interrupt
    FPUEH_IRQHandler,        // 34: FPUEH Interrupt
    SMU_IRQHandler,        // 35: SMU Interrupt
    WTIMER0_IRQHandler,        // 36: WTIMER0 Interrupt
    WTIMER1_IRQHandler,        // 37: WTIMER1 Interrupt
    PCNT1_IRQHandler,        // 38: PCNT1 Interrupt
    PCNT2_IRQHandler,        // 39: PCNT2 Interrupt
    USART2_RX_IRQHandler,        // 40: USART2_RX Interrupt
    USART2_TX_IRQHandler,        // 41: USART2_TX Interrupt
    I2C1_IRQHandler,        // 42: I2C1 Interrupt
    USART3_RX_IRQHandler,        // 43: USART3_RX Interrupt
    USART3_TX_IRQHandler,        // 44: USART3_TX Interrupt
    VDAC0_IRQHandler,        // 45: VDAC0 Interrupt
    CSEN_IRQHandler,        // 46: CSEN Interrupt
    LESENSE_IRQHandler,        // 47: LESENSE Interrupt
    CRYPTO1_IRQHandler,        // 48: CRYPTO1 Interrupt
    TRNG0_IRQHandler,        // 49: TRNG0 Interrupt
    0,                         // 50: Reserved
};

// ----------------------------------------------------------------------------

// Processor ends up here if an unexpected interrupt occurs or a
// specific handler is not present in the application code.
// When in DEBUG, trigger a debug exception to clearly notify
// the user of the exception and help identify the cause.

void __attribute__ ((section(".after_vectors")))
Default_Handler(void)
{
#if defined(DEBUG)
__DEBUG_BKPT();
#endif
while (1)
  {
  }
}

// ----------------------------------------------------------------------------
