//
// Copyright (c) 2015 Liviu Ionescu.
// This file was automatically generated by the xPacks scripts.
//

// The list of external handlers is from the ARM assembly startup files.

// ----------------------------------------------------------------------------

#include <cmsis-plus/cortexm/exception-handlers.h>

// ----------------------------------------------------------------------------

void __attribute__((weak))
Default_Handler(void);

// Forward declaration of the specific IRQ handlers. These are aliased
// to the Default_Handler, which is a 'forever' loop. When the application
// defines a handler (with the same name), this will automatically take
// precedence over these weak definitions

void __attribute__ ((weak, alias ("Default_Handler")))
DMA_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_EVEN_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USB_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ACMP0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ADC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
DAC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_ODD_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER3_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LESENSE_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART2_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART2_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART0_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART0_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART1_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
UART1_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LEUART0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LEUART1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LETIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT2_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RTC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
BURTC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
VCMP_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LCD_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
MSC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
AES_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EBI_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
EMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
FPUEH_IRQHandler(void);

// ----------------------------------------------------------------------------

extern unsigned int _estack;

typedef void
(* const pHandler)(void);

// ----------------------------------------------------------------------------

// The table of interrupt handlers. It has an explicit section name
// and relies on the linker script to place it at the correct location
// in memory.

__attribute__ ((section(".isr_vector"),used))
pHandler __isr_vectors[] =
  {
    // Cortex-M Core Handlers
    (pHandler) &_estack,               // The initial stack pointer
    Reset_Handler,                     // The reset handler

    NMI_Handler,                       // The NMI handler
    HardFault_Handler,                 // The hard fault handler

#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    MemManage_Handler,                 // The MPU fault handler
    BusFault_Handler,                  // The bus fault handler
    UsageFault_Handler,                // The usage fault handler
#else
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    SVC_Handler,                       // SVCall handler
#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    DebugMon_Handler,                  // Debug monitor handler
#else
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    PendSV_Handler,                    // The PendSV handler
    SysTick_Handler,                   // The SysTick handler

    // ----------------------------------------------------------------------
    // External Interrupts
    DMA_IRQHandler,        // 0: DMA Interrupt
    GPIO_EVEN_IRQHandler,        // 1: GPIO_EVEN Interrupt
    TIMER0_IRQHandler,        // 2: TIMER0 Interrupt
    USART0_RX_IRQHandler,        // 3: USART0_RX Interrupt
    USART0_TX_IRQHandler,        // 4: USART0_TX Interrupt
    USB_IRQHandler,        // 5: USB Interrupt
    ACMP0_IRQHandler,        // 6: ACMP0 Interrupt
    ADC0_IRQHandler,        // 7: ADC0 Interrupt
    DAC0_IRQHandler,        // 8: DAC0 Interrupt
    I2C0_IRQHandler,        // 9: I2C0 Interrupt
    I2C1_IRQHandler,        // 10: I2C1 Interrupt
    GPIO_ODD_IRQHandler,        // 11: GPIO_ODD Interrupt
    TIMER1_IRQHandler,        // 12: TIMER1 Interrupt
    TIMER2_IRQHandler,        // 13: TIMER2 Interrupt
    TIMER3_IRQHandler,        // 14: TIMER3 Interrupt
    USART1_RX_IRQHandler,        // 15: USART1_RX Interrupt
    USART1_TX_IRQHandler,        // 16: USART1_TX Interrupt
    LESENSE_IRQHandler,        // 17: LESENSE Interrupt
    USART2_RX_IRQHandler,        // 18: USART2_RX Interrupt
    USART2_TX_IRQHandler,        // 19: USART2_TX Interrupt
    UART0_RX_IRQHandler,        // 20: UART0_RX Interrupt
    UART0_TX_IRQHandler,        // 21: UART0_TX Interrupt
    UART1_RX_IRQHandler,        // 22: UART1_RX Interrupt
    UART1_TX_IRQHandler,        // 23: UART1_TX Interrupt
    LEUART0_IRQHandler,        // 24: LEUART0 Interrupt
    LEUART1_IRQHandler,        // 25: LEUART1 Interrupt
    LETIMER0_IRQHandler,        // 26: LETIMER0 Interrupt
    PCNT0_IRQHandler,        // 27: PCNT0 Interrupt
    PCNT1_IRQHandler,        // 28: PCNT1 Interrupt
    PCNT2_IRQHandler,        // 29: PCNT2 Interrupt
    RTC_IRQHandler,        // 30: RTC Interrupt
    BURTC_IRQHandler,        // 31: BURTC Interrupt
    CMU_IRQHandler,        // 32: CMU Interrupt
    VCMP_IRQHandler,        // 33: VCMP Interrupt
    LCD_IRQHandler,        // 34: LCD Interrupt
    MSC_IRQHandler,        // 35: MSC Interrupt
    AES_IRQHandler,        // 36: AES Interrupt
    EBI_IRQHandler,        // 37: EBI Interrupt
    EMU_IRQHandler,        // 38: EMU Interrupt
    FPUEH_IRQHandler,        // 39: FPUEH Interrupt
};

// ----------------------------------------------------------------------------

// Processor ends up here if an unexpected interrupt occurs or a
// specific handler is not present in the application code.
// When in DEBUG, trigger a debug exception to clearly notify
// the user of the exception and help identify the cause.

void __attribute__ ((section(".after_vectors")))
Default_Handler(void)
{
#if defined(DEBUG)
__DEBUG_BKPT();
#endif
while (1)
  {
  }
}

// ----------------------------------------------------------------------------
