//
// Copyright (c) 2015 Liviu Ionescu.
// This file was automatically generated by the xPacks scripts.
//

// The list of external handlers is from the ARM assembly startup files.

// ----------------------------------------------------------------------------

#include <cmsis-plus/cortexm/exception-handlers.h>

// ----------------------------------------------------------------------------

void __attribute__((weak))
Default_Handler(void);

// Forward declaration of the specific IRQ handlers. These are aliased
// to the Default_Handler, which is a 'forever' loop. When the application
// defines a handler (with the same name), this will automatically take
// precedence over these weak definitions

void __attribute__ ((weak, alias ("Default_Handler")))
DMA_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_EVEN_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ACMP0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
ADC0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
I2C0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
GPIO_ODD_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER1_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART1_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
LEUART0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
PCNT0_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
RTC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
CMU_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
VCMP_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
MSC_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
AES_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_RX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USART0_TX_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
USB_IRQHandler(void);
void __attribute__ ((weak, alias ("Default_Handler")))
TIMER2_IRQHandler(void);

// ----------------------------------------------------------------------------

extern unsigned int _estack;

typedef void
(* const pHandler)(void);

// ----------------------------------------------------------------------------

// The table of interrupt handlers. It has an explicit section name
// and relies on the linker script to place it at the correct location
// in memory.

__attribute__ ((section(".isr_vector"),used))
pHandler __isr_vectors[] =
  {
    // Cortex-M Core Handlers
    (pHandler) &_estack,               // The initial stack pointer
    Reset_Handler,                     // The reset handler

    NMI_Handler,                       // The NMI handler
    HardFault_Handler,                 // The hard fault handler

#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    MemManage_Handler,                 // The MPU fault handler
    BusFault_Handler,                  // The bus fault handler
    UsageFault_Handler,                // The usage fault handler
#else
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    0,                                 // Reserved
    SVC_Handler,                       // SVCall handler
#if defined(__ARM_ARCH_7M__) || defined(__ARM_ARCH_7EM__)
    DebugMon_Handler,                  // Debug monitor handler
#else
    0,                                 // Reserved
#endif
    0,                                 // Reserved
    PendSV_Handler,                    // The PendSV handler
    SysTick_Handler,                   // The SysTick handler

    // ----------------------------------------------------------------------
    // External Interrupts
    DMA_IRQHandler,        // 0: DMA Interrupt
    GPIO_EVEN_IRQHandler,        // 1: GPIO_EVEN Interrupt
    TIMER0_IRQHandler,        // 2: TIMER0 Interrupt
    ACMP0_IRQHandler,        // 3: ACMP0 Interrupt
    ADC0_IRQHandler,        // 4: ADC0 Interrupt
    I2C0_IRQHandler,        // 5: I2C0 Interrupt
    GPIO_ODD_IRQHandler,        // 6: GPIO_ODD Interrupt
    TIMER1_IRQHandler,        // 7: TIMER1 Interrupt
    USART1_RX_IRQHandler,        // 8: USART1_RX Interrupt
    USART1_TX_IRQHandler,        // 9: USART1_TX Interrupt
    LEUART0_IRQHandler,        // 10: LEUART0 Interrupt
    PCNT0_IRQHandler,        // 11: PCNT0 Interrupt
    RTC_IRQHandler,        // 12: RTC Interrupt
    CMU_IRQHandler,        // 13: CMU Interrupt
    VCMP_IRQHandler,        // 14: VCMP Interrupt
    MSC_IRQHandler,        // 15: MSC Interrupt
    AES_IRQHandler,        // 16: AES Interrupt
    USART0_RX_IRQHandler,        // 17: USART0_RX Interrupt
    USART0_TX_IRQHandler,        // 18: USART0_TX Interrupt
    USB_IRQHandler,        // 19: USB Interrupt
    TIMER2_IRQHandler,        // 20: TIMER2 Interrupt
};

// ----------------------------------------------------------------------------

// Processor ends up here if an unexpected interrupt occurs or a
// specific handler is not present in the application code.
// When in DEBUG, trigger a debug exception to clearly notify
// the user of the exception and help identify the cause.

void __attribute__ ((section(".after_vectors")))
Default_Handler(void)
{
#if defined(DEBUG)
__DEBUG_BKPT();
#endif
while (1)
  {
  }
}

// ----------------------------------------------------------------------------
